version: '3'
services:
  bitzenyd:
    container_name: bitzenyd
    volumes:
      - './data/.bitzeny:/home/bitcoin/.bitzeny'
    ports:
      - '9252:9252'
    build: coind
#    image: nao20010128nao/docker-bitzenyd:alpine

  electrumx:
    container_name: bitzeny-electrumx
    volumes:
      - './data/electrumx:/data'
    environment:
      - 'DAEMON_URL=http://user:pass@localhost:9252'
      - COIN=Bitzeny
    ports:
      - '50002:50002'
    build: electrumx